
name: Build and Upload Paperclip

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Paper
      run: |
        ./paper patch
        ./paper jar
    - name: Upload Paperclip
      uses: actions/upload-artifact@v2.1.4
      with:
        # Artifact name
        name: Paperclip
        # A file, directory or wildcard pattern that describes what to upload
        path: paperclip.jar
        if-no-files-found: error
